### ISSUE TITLE
Docker 安装 ShadowSocks

### ISSUE THREAD

**Issue by bingoogolapple** [bingoogolapple/bingoogolapple.github.io#193]
### 安装 Docker

* 更新 yum
```
sudo yum update
```
* 通过脚本安装 Docker
```
curl -fsSL https://get.docker.com/ | sh
```
* 启动 Docker 进程
```
sudo service docker start
```
* 停止 Docker 进程
```
sudo service docker stop
```

**Comment by bingoogolapple** [comment]
#### 制作 ShadowSocks 镜像

* 拉取 centos:7.2.1511 镜像
```
docker pull centos:7.2.1511
```
* 基于 centos:7.2.1511 镜像以交互式启动名叫 bga-ss 的容器
```
docker run -it --name bga-ss centos:7.2.1511 bash
```
* 临时有事停掉容器后，再次使用时可以以交互方式重新启动容器 bga-ss
```
docker start -i bga-ss
```
* 以交互方式启动容器后，通过以下步骤可以使容器在后台运行
```
先 ctrl + p
然后 ctrl + q
```
* 进入后台运行的容器 bga-ss
```
docker attach bga-ss
```

**Comment by bingoogolapple** [comment]
### [安装 ShadowSocks](https://github.com/shadowsocks/shadowsocks/wiki/Shadowsocks-%E4%BD%BF%E7%94%A8%E8%AF%B4%E6%98%8E)

* 更新 yum
```
sudo yum update
```
* 安装 pip
```
yum install python-setuptools && easy_install pip
```
* 安装 ShadowSocks
```
pip install shadowsocks
```

**Comment by bingoogolapple** [comment]
### 多账户管理

#### 准备 screen

* 安装 screen
```
yum install screen
rpm -qa|grep screen
```
* 查看会话列表
```
screen -list
```
* 杀死进程
```
kill -9 进程号
```
* 清除被杀死的会话
```
screen -wipe
```

#### 安装 Node.js

* 安装 nvm
```
curl -o- https://raw.githubusercontent.com/creationix/nvm/v0.33.0/install.sh | bash
```
* 安装 Node 6
```
nvm install 6
```
* 安装 ShadowSocks-Manager
```
npm i -g shadowsocks-manager
```

#### 运行 ssmgr

* 开启 ShadowSocks。如果没有提示 started，则先执行 ssserver -d stop
```
ssserver -m rc4-md5 -p 端口1 -k 密码1 --manager-address 127.0.0.1:端口2 -d start
```
* mkdir ~/.ssmgr
* vim ~/.ssmgr/ss.yml
```
type: s

shadowsocks:
  address: 127.0.0.1:端口2
manager:
  address: 0.0.0.0:端口3
  password: '密码2'
db: 'ss.sqlite'
```
* vim ~/.ssmgr/webgui.yml
```
type: m

manager:
  address: IP地址:端口3
  password: '密码2'
plugins:
  flowSaver:
    use: true
  user:
    use: true
  account:
    use: true
  macAccount:
    use: true
  group:
    use: true
  email:
    use: true
    type: 'smtp'
    username: '邮箱'
    password: '邮箱密码'
    host: 'smtp.163.com'
  webgui:
    use: true
    host: '0.0.0.0'
    port: '80'
    site: 'ip地址或域名'

db: 'webgui.sqlite'
```
* screen -dmS ssmgr ssmgr -c ~/.ssmgr/ss.yml
* screen -dmS webgui ssmgr -c ~/.ssmgr/webgui.yml
* 别名 vim ~/.bashrc
```
alias startssserver='ssserver -m rc4-md5 -p 端口 -k 密码 --manager-address 127.0.0.1:端口2 -d start'
alias stopssserver='ssserver -d stop'

alias startssmgr='screen -dmS ssmgr ssmgr -c ~/.ssmgr/ss.yml'
alias startssmgrui='screen -dmS webgui ssmgr -c ~/.ssmgr/webgui.yml'
```
